title: McSohan's Blog
email: your-email@example.com
description: >-
  Personal blog for tracking activities and technical explorations.
baseurl: ""
url: "https://mcsohan.github.io"
theme: minima
plugins:
  - jekyll-feed
